version: '2'
services:
  web: &web
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    volumes:
    - .:/app
    - "${HOME}/Documents/continuum/transbank/sdk/transbank-sdk-python/:/transbank-sdk-python"
    volumes_from:
      - python_cache
    ports:
    - "5000:5000"
    environment:
      - FLASK_APP=/app/__init__.py
      - FLASK_ENV=development

  python_cache:
    image:  tiangolo/uwsgi-nginx-flask:python3.7-alpine3.7
    volumes:
    - /usr/local/lib/python3.7/site-packages